---
title: "Groups"
author: "Lars Relund Nielsen"
date: "17/8/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      # cache = TRUE, autodep = TRUE,
                      fig.width = 10, fig.height = 7)
library(tidyverse)
library(readxl)
library(ggraph)
library(igraph)
library(tidygraph)
library(visNetwork)
```

The groups spreadsheet must be saved in the `cplex` subfolder. First run cplex (or run it from OPL Studio and set `eval=FALSE`):

```{r, include=FALSE}
# minimal example
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))
visNetwork(nodes, edges, width = "100%")
```


```{r, eval=FALSE, cache=FALSE}
oplPath <- "C:/tools/CPLEX_Studio127/opl/bin/x64_win64/oplrun"
res <- system(str_c(oplPath, " -p ", 'cplex/group_allocation "Opt and find alternative solutions"'))
if (res != 0) cat("Problems with OPL model. Have a look at it in OPLStudio!")
```

Next, we plot some of the best solutions:

```{r, warning=FALSE, message=FALSE, fig.keep='all', out.width="100%", results='asis'}
sol_files <- list.files(pattern = "plot_node.*_c=.*csv")
res <- tibble(file = sol_files,
              groups = sol_files %>% 
                 str_replace("^(.*?g)(.*?)(_.*.csv)$", "\\2"), 
              solution = sol_files %>% 
                 str_replace("^(.*s)(.*?)(_.*.csv)$", "\\2"), 
              cost = sol_files %>% 
                 str_replace("^(.*?c=)(.*)(.csv)$", "\\2")) %>% 
   type.convert() %>% 
   slice_min(cost) %>% 
   arrange(groups)
res <- bind_rows(res %>% slice_head(n=3), res %>% slice_tail(n=3))
   
create_groups <- function(fNames, visN = T) {
   dat <- read_excel("cplex/group_allocation/group_allocation.xlsx")
   studNames <- dat %>% pull(1) %>% str_replace_all("(^.*? )(.)(.*)", "\\1\\2")
   dat <- dat %>% select(-(1:4))
   adj_mat <- dat %>% replace(is.na(.), 0) %>% as.matrix()
   g <- adj_mat %>% 
      graph_from_adjacency_matrix(mode = "undirected") %>% 
      as_tbl_graph() %>% 
      activate(nodes) %>% 
      mutate(name = studNames) %>% 
      activate(edges) %>% 
      mutate(wish = T)
   for (f in fNames) {
      fS <- str_remove(f, ".csv")
      message(fS)
      sol <- read_csv2(file = f, locale = locale(encoding = "latin1"), col_types = cols()) %>% 
         arrange(Id)
      g <- g %>% 
         activate(nodes) %>% 
         mutate(group = sol$Group, gName = str_c("G", group, ":", name, "(", row_number(), ")", sep="")) 
      # edgesSol <- sol %>% 
      #    group_by(Group) %>% 
      #    nest() %>% 
      #    mutate(edges = map(data, function(df) {expand_grid(to = df$Id, from = df$Id)})) %>% 
      #    pull(edges) %>% 
      #    bind_rows() %>% 
      #    mutate(wish = F)
      # g <- g %>% 
      #    activate(edges) %>% bind_edges(edgesSol) %>% distinct()
      if (!visN) {
         plt <- ggraph(g, layout = 'fr') + 
            geom_edge_link(aes(color = wish)) +
            geom_node_label(aes(colour = as.factor(group), label = gName), size = 2) +
            ggtitle(fS) +
            theme_graph() + 
            theme(legend.position = "none")
         # png(file = str_c(fS, ".png"), width = 1000, height = 1000)
         print(plt)
         # dev.off() 
      } else {
         edges <- g %>% activate(edges) %>% as_tibble()
         nodes <- g %>% activate(nodes) %>% as_tibble()
         nodes <- bind_cols(id = 1:nrow(nodes), nodes)
         colnames(nodes) <- c("id", "name", "group", "label")
         vn <- visNetwork(nodes, edges, main = fS, width = "100%") %>% 
            visOptions(selectedBy = "group", 
                highlightNearest = TRUE,
                nodesIdSelection = TRUE
            ) %>%
            visPhysics(stabilization = FALSE) %>% 
            visEdges(smooth = FALSE) %>% 
            visIgraphLayout()
         print(htmltools::tagList(vn))
      }
   }
}
create_groups(res$file)
```

Groups:

```{r}
sol <- read_csv2(file = as.character(res$file[1]), locale = locale(encoding = "latin1"), col_types = cols()) %>% 
   group_by(Group) %>% 
   nest() %>% 
   # mutate(Names = str_c("Group ", Group, ": ", map_chr(data, function(df) {str_c(df$Label, " (", df$Id, ")", collapse = ", ")})))
   mutate(Names = str_c("Group ", Group, ": ", map_chr(data, function(df) {str_c(df$Label, collapse = ", ")})))
cat(str_c(sol$Names, collapse = "\n"))
```



The result file:

```{r, cache=FALSE}
cat(read_file("results.txt", locale = locale(encoding = "latin1")))
```

