---
title: "Tools for Analytics - Eval"
author: "Lars Relund Nielsen"
output:
  xaringan::moon_reader:
    css: "./libs/slides.css"
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      highlightStyle: solarized-light
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---

```{r, child = "setup.Rmd", echo=FALSE}
```

```{r include=FALSE}
# use xaringan::inf_mr(cast_from = ".") to preview
```

## Official evaluation of the course

* You should have received a link.
* Use the next 10 minutes to give feedback.
* If you have comments then give them in a constructive way:
  - what could be improved
  - how could it be done
  - what should be left out 


```{r copy, include=FALSE}
file.copy(list.files(pattern = ".html"), "../docs/slides/", overwrite = T)
file.copy("./slides.css", "./libs/", overwrite = T)
file.copy("libs", "../docs/slides/", recursive = T)
file.copy("img", "../docs/slides/", recursive = T)
system2("Rscript", args = "-e 'rmarkdown::render(\"index.Rmd\", quiet = TRUE)'")
```

```{r links, child="links.md", include=FALSE}
```