```{r, code = readLines("common.R"), cache = FALSE, include=FALSE}
```


# (PART) R project {-} 

# Mandatory R project {#mod-r-project}

## Learning outcomes {#lo-project}

By the end of this module, you are expected to have:

* Know how the assignment is given.
* Know how your group report is handed in.
* Know how to peer grade other groups' report.

After handing in and grading the report you should have practiced:

* How to manage a code in a collaborative working environment.	
* Handling data such as import, tidy, transform, visualize and export. 						
* Developing well-structured code. 						
* Performing testing and debugging. 						
* How to implement/code selected algorithms. 						
* Applying analytical techniques on data.						
* Applying relevant methods, algorithms and techniques from this course in order to solve a specific problem.						
* Independently handling data. 						
* Independently analyzing data given a relevant research question.						
* Interpreting and discuss results based on a data analysis in relation to the relevant academic literature.						
* Communicating results from applied research in a scientific way, e.g. using literate programming.		

The learning outcomes relate to the [overall learning goals](#lg-course) number 6-14, 17 and 18 of the course.

<!-- SOLO increasing: identify · memorise · name · do simple procedure · collect data · -->
<!-- enumerate · describe · interpret · formulate · list · paraphrase · combine · do -->
<!-- algorithms · compare · contrast · explain causes · analyse · relate · derive · -->
<!-- evaluate · apply · argue · theorise · generalise · hypothesise · solve · reflect -->


## R project

In week 49 you must write a mandatory R project in groups. Moreover, for being qualified for exam participation each student must do individual peer grading using the on-line platform [Peergrade]. The assignment will be available in the system at the opening time. It will be provided in R Markdown and include a description of the different questions which must be answered and links to the data sources needed.

**You must hand in the assignment in groups**. That is, each group only hands in once, and simply select the group members from a list in the system. Make sure to do this very carefully! Each group must hand in the R Markdown source file and the rendered html file.

When the peer-grading period starts, you must do peer evaluation based on a guiding solution of the project assignment. **This step is done individually**.

The schedule for the project assignment is:

Time  | Description
------------- | -------------
26/11 8:00: | Assignment becomes available.
During week 48-49: | See the schedule for study cafes. 
09/12 24:00: | Deadline for handing in your solution in [Peergrade]. 
09/12 24:00: | Peer grading starts.
13/12 24:00: | Deadline for completing the peer grading in [Peergrade].

It is important that you use your university email as login, so we can identify you i [Peergrade]. Please find a guide on how to use the system [here](https://help.peergrade.io/en/collections/437178-getting-started).

 







