```{r, include=FALSE, cache=FALSE}
source("common.R")
```


# Install git and GitHub {#mod-git}

## Learning outcomes

By the end of this module, you are expected to have:

* Installed git.
* Signed up for GitHub.
* Tested Git and GitHub in RStudio.

## Install and signup

<!-- https://happygitwithr.com/big-picture.html -->
Git is a version control system. Git manages the evolution of a set of files – called a repository – in a sane, highly structured way. If you have no idea what I'm talking about, think of it as the "Track Changes" features from Microsoft Word on steroids. 

GitHub provide a home for your Git-based projects on the internet. If you have no idea what I'm talking about, think of it as DropBox but much, much better. It allows other people to see your stuff, sync up with you, and perhaps even make changes. Even for private solo projects, it’s a good idea to push your work to a remote location for peace of mind.

We are going to Git and GitHub for maintaining the R code you produce in the groups.

<div class = "boxTask">
`r addIcon("tasks", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))`  


* Install the desktop version of [RStudio][rstudio-download], a powerful user interface for R. 
</div>

## Resources


   
