```{r include = FALSE, cache=FALSE}
source("common.R")
```


# Functions


[Intro]

## Learning outcomes

By the end of this module, you are expected to be able to:

* Call a function.
* Formulate a function with different input arguments.
* Describe why functions are important in R.
* Set defaults for input arguments. 
* Return values from functions.
* Explain how variable scope and precedence works.
* Document functions. 


data type comparison with VBA

<!-- SOLO increasing: identify · memorise · name · do simple procedure · collect data · -->
<!-- enumerate · describe · interpret · formulate · list · paraphrase · combine · do -->
<!-- algorithms · compare · contrast · explain causes · analyse · relate · derive · -->
<!-- evaluate · apply · argue · theorise · generalise · hypothesise · solve · reflect -->


## DataCamp course

DataCamp course [Introduction to Writing Functions in R][datacamp-r-functions] or Chapter 3 in DataCamp course [Intermediate R][intermediate-r]

An excellent introduction to conditionals and if statements is given in Chapter 1 of the DataCamp course [Intermediate R][intermediate-r]. Please complete the chapter before continuing. 




<!-- ### Tasks -->

<!-- ### Online Tasks/activitites -->

<!-- <div class = "boxTask"> -->
<!-- `r addIcon("tasks", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))`   -->

<!--    * dasf -->
<!--    * fsa -->
<!--    * 324 -->
<!-- </div> -->

## Different learning paths

`r strLPath`

* Suggestion 1 
* Suggestion 2

## Exercises

### Exercise ()

<!-- <div class = "boxExercise"> -->
<!-- `r addIcon("laptop-code", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))`   -->

<!-- **Exercise 1** -->
<!-- asdf asdlfkj sdfklj fsdjka æ -->

<!--    1. sdf -->
<!--    2. edasf -->

<!-- **Exercise 2** -->
<!-- asdfav sdaf sdhj sdjkahdf jkhasdkjæsdfh asjf -->

<!--    1. sdf -->
<!--    2. sdf -->
<!-- </div> -->


<!-- `r addIcon("file-code", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))` -->
<!-- `r addIcon("code", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))` -->
<!-- `r addIcon("external-link-alt", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))` -->

## Resources






