```{r, code = readLines("common.R"), cache = FALSE, include=FALSE}
```

# (PART) Getting started  {-} 

[MOVED TO BB]

# Signup for online resources {#sec:signup}

During the course we are going to use a set of online resources that you will need to sign up to. If you already have an account at some of the places you may use your current account.

## Learning outcomes

By the end of this module, you are expected to have:

* Signed up to Peergrade.
* Signed up to Datacamp.
<!-- * Signed up to GitHub. -->
* Signed up to Udemy.
* Added your group preferences.
* Signed up for the course using the online form.

## Online Tasks/activitites

[Peergrade] is an online platform for peer feedback activities and automates most of the process. We are going to use Peergrade in the two mandatory home assignments. You will handin your assignment in groups and do individual peer feedback.

[Datacamp] is an online platform for learning data science. We are going to use the platform for online lessons and exercises in the R part of the course.

[Udemy] is an online learning platform with different online courses. We are going to use Udemy in the VBA part of the course. 

<div class = "boxTask">
`r addIcon("tasks", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))`  

   * Sign-up for the course "[Tools for analytics][peergrade-signup]" at Peergrade using course code XE7FMM. Sign-up using the institutional AU login.
   * Sign-up for Udemy using your gift code (BESKREVELSE AF HVORDAN MAN FÅR DEN)
   * Sign-up for the course "[Tools for analytics][datacamp-signup]" at Datacamp. Note you have to use your university e-mail with domain `post.au.dk`.
   * Add your preferences about group work in the [Google sheet][google-grupper]. 
   * Fill out the [online form][google-form].
</div>

Remember your user names and passwords!




<!-- ## Exercises -->

<!-- <div class = "boxExercise"> -->
<!-- `r addIcon("laptop-code", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))`   -->

<!-- **Exercise 1** -->
<!-- asdf asdlfkj sdfklj fsdjka æ -->

<!--    1. sdf -->
<!--    2. edasf -->

<!-- **Exercise 2** -->
<!-- asdfav sdaf sdhj sdjkahdf jkhasdkjæsdfh asjf -->

<!--    1. sdf -->
<!--    2. sdf -->
<!-- </div> -->


<!-- `r addIcon("file-code", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))` -->
<!-- `r addIcon("code", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))` -->
<!-- `r addIcon("external-link-alt", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))` -->

<!-- ## Resources -->