```{r, code = readLines("common.R"), cache = FALSE, include=FALSE}
```





# Transforming data {#sec-transform}

## Learning outcomes

By the end of this module, you are expected to be able to:

* Describe what tidy and wangling is.
* Apply the most common string functions
* Apply tidy operations to data 
* Transform data
* Clean data


<!-- SOLO increasing: identify · memorise · name · do simple procedure · collect data · -->
<!-- enumerate · describe · interpret · formulate · list · paraphrase · combine · do -->
<!-- algorithms · compare · contrast · explain causes · analyse · relate · derive · -->
<!-- evaluate · apply · argue · theorise · generalise · hypothesise · solve · reflect -->


## Tidy 


## Wangling


https://learn.datacamp.com/projects/758

## Different learning paths

`r strLPath`

* Suggestion 1 
* Suggestion 2

## Recap

[Summary of learning]



## Exercises


## Resources

[Links to further resources]






<!-- Usefull stuff: 

Icons:
`r addIcon("file-code", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))`
`r addIcon("code", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))`
`r addIcon("external-link-alt", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))`



Task/checklist box:
<div class = "boxTask">
`r addIcon("tasks", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))`

   * dasf
   * fsa
   * 324
</div>



Exercise box:
<div class = "boxExercise">
`r addIcon("laptop-code", attrib = list(class = "fa-pull-right fa-5x iconStyle1"))`  

**Exercise 1**
asdf asdlfkj sdfklj fsdjka æ

   1. sdf
   2. edasf

**Exercise 2**
asdfav sdaf sdhj sdjkahdf jkhasdkjæsdfh asjf

   1. sdf
   2. sdf
</div>



Numbered exercises with hints:
## Exercises

Exercises are numbered using [module number].[section number].[exercise number]. 

### Exercise (install packages)

This exercise is done from the Console in RStudio. 

   1) Install the package `devtools` using function `install.packages`. Note you can always get help/see documentation by typing `?install.packages` or typing `install.packages` and press F1. 
   
You now have install the package from the default repository ([CRAN][cran]). You may also install packages from other repositories (e.g. GitHub)
   
   1) Have a look at the documentation for function `install_github` in the package `devtools`. This can be done in different ways:
   
```r
library(devtools)    # we here load all the functions in devtools 
?install_github

?devtools::install_github     # we here use the namespace devtools to load only one function
```

   1) Install the package `tfa` from github using path ``

```{r}
# filter the flights table to include only United and
# American flights

```

```{r}
{
sink("tmp.md")
cat('
Vi tester
```r
cat("hello")
cat("world")
```')
sink()
}
bs_modal(id = "hint", title = "Hint", 
         body = includeMarkdown("tmp.md"))
```

```{r}
bs_button("Hint") %>%
  bs_attach_modal(id_modal = "hint")
```

### Exercise

[Add text]

### Exercise ()

[Add text]

### Exercise (string management)




-->