---
title: "Setting up a queue system for a course"
author: "Lars Relund Nielsen"
date: "10/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The course Tools for Analytics use a queue system set up in Airtable which is an online site for maintaining a database.

## Setup

   1) Sign-up for [Airtable](https://airtable.com/) (teacher and instructors). It is a good idea to upload your picture under your settings so that it will be shown when an instructor is assigned to the queue. 
   2) [Copy the database template](https://airtable.com/shrzhqe7zuK2yPcIx) (one of the signed up persons).
   3) [Add the other users as collabarators](https://support.airtable.com/hc/en-us/articles/202625759-Adding-a-base-collaborator) using the share button. 
   4) Go to the `Queue signup` view (left) and press the `Share form` button. You can now copy a link to the form (that can be parsed to the students) or choose `Embed this form on your site`, copy the code and paste it into Blackboard (use the html view on a BB page). 
   
The form will look as follows:
      
<iframe class="airtable-embed" src="https://airtable.com/embed/shrku9dWOH5yDKYSr?backgroundColor=blue" frameborder="0" onmousewheel="" width="100%" height="533" style="background: transparent; border: 1px solid #ccc;"></iframe>

   5) Go to the `Current queue` view (left) and press the `Share view` button. You can now copy a link (that can be parsed to the students) or choose `Embed this view on your site`, copy the code and paste it into Blackboard (use the html view on a BB page). 
      
The view will look as follows:
      
<iframe class="airtable-embed" src="https://airtable.com/embed/shr0x6Yc2hScFnz9D?backgroundColor=blue&viewControls=on" frameborder="0" onmousewheel="" width="100%" height="533" style="background: transparent; border: 1px solid #ccc;"></iframe>

## Student usage

When a study cafe starts the students just use the links or embedded pages above to join the queue and see the current queue. Remember to inform them about refreshing the queue in the browser by e.g. pressing F5. 


## Instuctor usage

When the study cafe starts the instructors log into Airtable and go to the `TA queue list`. Choose the first item in the queue with `Status` = `In queue` and

   1) Set your name in the `TA assigned` column,
   2) Set the `Status` to `In progress`,
   3) Join the Zoom meeting using the link provided by the students.
   
When you have finished helping the students set the `Status` to `Done` and help the next group in the queue.

You may after the study cafe delete the records/rows with status `Done`.


## Customization

You can customize the look of the queue by changing the form and database names.